import Link from 'next/link';

export const metadata = {
  title: 'Affiliate & sponsored listing disclosures — Mattress Match Score',
};

export default function DisclosuresPage() {
  return (
    <div>
      <header className="page-hero">
        <div className="wrap">
          <span className="eyebrow">Policies</span>
          <h1 className="ph-title">Affiliate &amp; sponsored listing disclosures</h1>
          <p className="ph-sub">How we make money, and how we keep it separate from what we recommend.</p>
        </div>
      </header>

      <section className="section">
        <div className="wrap disc-wrap">
          <div className="disc-block">
            <h3>
              <span className="disc-ic">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <circle cx="12" cy="12" r="9" />
                  <path d="M12 7v10M9.5 9.5c0-1.4 1.2-2.5 2.5-2.5s2.5.8 2.5 2c0 1.5-1.5 2-2.5 2.3-1.3.4-2.5 1-2.5 2.7 0 1.2 1.2 2 2.5 2s2.5-.9 2.5-2.3" />
                </svg>
              </span>
              How we make money
            </h3>
            <p>
              Mattress Match Score is free to use. We earn a commission when you buy through certain links on this
              site, and some listings are paid placements from mattress brands and retailers. Neither arrangement is
              required for a mattress to appear in your results.
            </p>
          </div>

          <div className="disc-block">
            <h3>
              <span className="disc-ic">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M10 14a4 4 0 0 0 5.66 0l2.34-2.34a4 4 0 0 0-5.66-5.66l-1 1M14 10a4 4 0 0 0-5.66 0L6 12.34a4 4 0 0 0 5.66 5.66l1-1" />
                </svg>
              </span>
              Affiliate links
            </h3>
            <p>
              &ldquo;View at retailer&rdquo; buttons route through an affiliate link. If you make a purchase, we may
              earn a commission at no additional cost to you. Affiliate links are tagged with tracking parameters so
              the retailer can credit the referral — they never change the price you pay.
            </p>
            <div className="callout-box">
              This site contains affiliate links. As an affiliate, we may earn a commission on qualifying purchases,
              in accordance with FTC guidelines on endorsements and disclosures.
            </div>
          </div>

          <div className="disc-block">
            <h3>
              <span className="disc-ic">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M3 11v2a2 2 0 0 0 2 2h1l4 4V5L6 9H5a2 2 0 0 0-2 2Z" />
                  <path d="M16 8a5 5 0 0 1 0 8" />
                </svg>
              </span>
              Sponsored listings
            </h3>
            <p>
              Brands and retailers can pay to appear in a labeled &ldquo;Sponsored&rdquo; slot. Sponsored listings
              are refreshed on a set schedule — the badge shows the date a listing&apos;s specs and pricing were last
              verified.
            </p>
            <div className="badge-examples">
              <span className="listing-badge badge-sponsored">Sponsored · verified Mar 2026</span>
              <span className="listing-badge badge-top">Top match — algorithmic</span>
            </div>
            <p style={{ marginTop: 16 }}>
              Sponsored slots are visually and structurally separate from algorithmic rankings — a sponsored listing
              is never blended into, or substituted for, a mattress&apos;s Match Score position.
            </p>
          </div>

          <div className="disc-block">
            <h3>
              <span className="disc-ic">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M12 2 3 6v6c0 5.5 3.8 9.7 9 10 5.2-.3 9-4.5 9-10V6Z" />
                  <path d="m8.5 12 2.2 2.2L15.5 9" />
                </svg>
              </span>
              Editorial independence
            </h3>
            <p>
              Match Scores are generated by the scoring model described in our{' '}
              <Link href="/methodology">methodology</Link>. Advertisers cannot purchase a higher score, alter
              sub-scores, or remove a risk flag.
            </p>
          </div>

          <div className="disc-block contact-block">
            <h3>Questions about a listing?</h3>
            <p>
              If something looks off — outdated pricing, a missing disclosure, a flag you disagree with — tell us
              and we&apos;ll look into it.
            </p>
            <a href="mailto:hello@mattressmatchscore.example" className="btn btn-ghost-dark">
              Contact the editorial team
            </a>
          </div>
        </div>
      </section>
    </div>
  );
}
